In [1]:
import numpy as np

Question 1
Given the following numpy array:

In [2]:
arr = np.array([1, 2, 3, 4, 5])

Write a Python code to multiply each element in the array by 2.
Answer:

In [3]:
arr * 2

array([ 2,  4,  6,  8, 10])

Question 2
Given the following 2D numpy array:

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

Write a Python code to select the second row of the array.

Answer:

In [5]:
arr[1:2]

array([[4, 5, 6]])

Question 3
Create a 2D numpy array of shape (5, 5) filled with the number 1.

Answer:

In [7]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Question 4
Given the following 2D numpy array:

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

Write a Python code to calculate the sum of all the elements in each row.

Answer:

In [ ]:
arr.sum(arr, axis=1)

45

Question 5
Given the following 2D numpy array:

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

Write a Python code to calculate the average of all the elements.

Answer: